{
  boolean exceptionOccurred=false;
  try {
    remoteTaskRunner.run(new TestTask(new String(new char[5000]),"dummyDs",Lists.<DataSegment>newArrayList(new DataSegment("dummyDs",new Interval(new DateTime(),new DateTime()),new DateTime().toString(),null,null,null,null,0)),Lists.<AggregatorFactory>newArrayList()),new TaskContext(new DateTime().toString(),Sets.<DataSegment>newHashSet(),Sets.<DataSegment>newHashSet()),null);
  }
 catch (  IllegalStateException e) {
    exceptionOccurred=true;
  }
  Assert.assertTrue(exceptionOccurred);
}
